### ISSUE TITLE
browser script please

### ISSUE THREAD

**Issue by JosePedroDias** [stevenmiller888/mind#6]
This module can work on the browser, right?
Please provide a built script somehere, either on a dist dir in master on a gh-pages branch. Thank you.

Tried to test-drive brain.js but couldn't make it link to the source:
https://jsbin.com/yamivi/edit?html,js

**Comment by stevenmiller888** [comment]
Thanks for bringing this up. Just added a note to the readme about using Mind in the browser. You can use the built `index.js` file in the root of this repo, which will expose `Mind` onto the `window` object.

Let me know if that clarifies things.

**Comment by JosePedroDias** [comment]
I tried that. Throws an exception related to the DOM. Check the jsbin (uncomment the script)

**Comment by stevenmiller888** [comment]
That's because the `src` attribute in your jsbin example is referencing the build script for the Mind website, rather than the build script for Mind itself.

I don't recommend hot-linking. However, if you want to get your jsbin example working quickly, you can use this workaround:

`<script type="text/javascript" src="https://rawgit.com/stevenmiller888/mind/master/index.js"></script>`

Hope that helps!

**Comment by JosePedroDias** [comment]
Check this out: https://output.jsbin.com/yamivi/latest/quiet

**Comment by stevenmiller888** [comment]
Nice dude! That's neat :)
