### ISSUE TITLE
Why its better?

### ISSUE THREAD

**Issue by gyzerok** [stevenmiller888/mind#9]
What is the key differences with Brain and why Mid is better?

**Comment by stevenmiller888** [comment]
Mind is not _better_ than Brain. Here are some key differences:
1. Brain allows an arbitrary number of hidden layers, while Mind currently does not.
2. Brain only allows the sigmoid function as the activation function, while Mind gives you the choice between the sigmoid and the hyperbolic tangent.
3. Mind abstracts out all the `for` loops and uses Matrix notation instead, which, in my opinion, makes the code a bit more readable.
4. Brain lets you train the network using a stream, while Mind currently does not.

So, I would definitely not say that Mind is better than Brain. In many ways, Brain is more sophisticated and I would absolutely recommend checking it out, as it is a great library. Mind shoots for code simplicity and network flexibility along with a nice API to work with.

Hope that clarifies things!

**Comment by gyzerok** [comment]
@stevenmiller888 thank you for such a detailed answer! 

So I have just one more question. What is a reason for 1?

**Comment by stevenmiller888** [comment]
Oh yeah, it's on my list (issue #1). I really want to focus on keeping the code in this library as simple and clear as possible, so that beginners can understand it. So, the reason it doesn't _yet_ allow an arbitrary number of hidden layers is because I haven't figured out a way to do it while keeping the code simple. It's something I want to figure out soon though. Let me know if that makes sense.

Sidenote: one problem that could arise is that the matrix multiplication part gets expensive pretty quickly when you add more layers and units per layer. So it might be worth figuring out a way to optionally parallelize the learning (maybe with web workers if in the browser and child processes if in Node.) Or might need to swap out the matrix library with something that can perform the operations on the GPU, although I'm not sure if that's possible. That could get us some seriously massive speedups on huge datasets.

Also, if you (or anyone) have any thoughts, concerns, or recommendations, would love to hear them all!

**Comment by stevenmiller888** [comment]
Just added the option to specify any number of hidden layers btw :)
